### PR TITLE
Handle empty strings with 2 commas

### PR DESCRIPTION
**Pull request by ridiculous**

### CODE REVIEW

**Comment by ridiculous** [comment]
@derrek Can i get a merge, plz?

**Comment by derrek** [comment]
@ridiculous the issue is a bit more complex than I thought when I first saw your pull request.  I brought in a lot of pull requests to the master branch and am trying to understand fully what's going on before I bring in this pull request. My instinct is that this should get fixed a bit further "upstream" in the code.

**Comment by ridiculous** [comment]
Come on, broh! Addresses can be all kinds of garbage, and the gem should be robust enough to handle it and not blow up. It's just one extra `if` statement ... :pray:

**Comment by derrek** [comment]
The currently released Gem v1.0.6 doesn't choke on the ", " or ", ,".  Master branch is choking but there's no gem of it yet.  That's why this is going to take me a while to understand.  It's all the other pull requests that I brought in against master, that I don't fully understand yet, that are causing this issue.

**Comment by ridiculous** [comment]
I see... That is a lil worrisome. I can't even use the current gem version cause it blows up trying to parse intersections like:
```ruby
StreetAddress::US.parse('NORTH AVE AND BEACH LOT, CHICAGO, IL').to_s
```
Whereas the master branch handles this gracefully, but doesn't handle an empty string with 2 commas :( ... Let me know if you want help investigating what's going on.

**Pull request closed without merging**
